feat: add the ability to export the project and check the export status
Megaputer/polyanalyst6api-py pull request #1
Opened 2023-05-30 15:10 UTC by stmikhayl

2023-05-30 15:31 UTC, yatmanov commented on polyanalyst6api/api.py
> +        Export a project from the PAserver.
конфликт с аргументом project_ids
что такое PAserver?
надо написать что экпортируется и куда

2023-05-30 15:34 UTC, yatmanov commented on polyanalyst6api/api.py
> +        :param file_path: full path to the exported file on the PA6 Drive, for example: "@administrator@/example.pa6"
этот path не full
экспортируется проект, не файл
файл ещё не экспортирован
PA6 надо убрать

2023-05-30 15:36 UTC, yatmanov commented on polyanalyst6api/api.py
> +        :param project_ids: id of projects to export
ids не id

2023-05-30 15:37 UTC, yatmanov commented on polyanalyst6api/api.py
> +        :param withND: include the source data              # the parameter will be depreceated soon
deprecated

2023-05-30 15:44 UTC, yatmanov commented on polyanalyst6api/api.py
> +                "usedParsers": usedParsers
одинарные кавычки

2023-05-30 17:20 UTC, stmikhayl commented on polyanalyst6api/api.py
> +            usedParsers: Optional[list] = [],  # the usedParsers must be a set but presented as a list
по итогу должно получиться что-то вроде ? 
`def export_project(self, export_parameters: dict, wait: bool)`
Если да, то причина в том, что параметров слишком много?

2023-05-31 06:59 UTC, yatmanov commented on polyanalyst6api/api.py
> +            usedParsers: Optional[list] = [],  # the usedParsers must be a set but presented as a list
да, и они у тебя сейчас обязательные

2023-05-31 09:35 UTC, yatmanov commented
Давай ещё перенесем оба метода в класс Project и скроем метод запроса статуса, добавив "_" в начало названия.

2023-05-31 15:31 UTC, stmikhayl commented on polyanalyst6api/api.py
> +            usedParsers: Optional[list] = [],  # the usedParsers must be a set but presented as a list
а может лучше передавать аргументы через распаковку словаря, оставив только один необязательный аргумент снаружи?
> def export_project(self, **kwargs, wait)

2023-06-01 08:25 UTC, stmikhayl commented
> Давай ещё перенесем оба метода в класс Project и скроем метод запроса статуса, добавив "_" в начало названия.

методы импорта не нужно же перемещать из класса API в класс Project?

2023-06-02 06:31 UTC, yatmanov commented
> методы импорта не нужно же перемещать из класса API в класс Project?

не нужно. Потом отдельно сделаю

2023-07-07 12:31 UTC, yatmanov commented
в папку .changes надо будет завести файл с названием *.feature и описанием что сделано в этом пулл реквесте

2023-08-03 13:48 UTC, yatmanov requested changes

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +        .. versionadded:: 0.27.1
след релиз будет 0.28.0

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +        Export a project from the Analytical Client to a drive.
понятно что Analytical Client, и не всегда на Drive; напиши просто: Export project to a file system

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +    def export(self, params: Dict[str, Any], wait: bool = False) -> Union[str, Dict[str, Any]]:
смысл заведения аргумента params в выделении и сокрытии необязательных параметров rest api в необязательный аргумент. А сейчас он у тебя обязательный
Нужно изменить на
`def export(self, filepath: str, params: Optional[Dict] = None, wait: bool = False) -> Union[str, Dict[str, Any]]:`

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +        params['multi'] = params.get('multi', False) # use the *.paar6 forma
Я не смог найти планы на удаление этих параметров. Можешь дать ссылку?

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +        params['ids'] = params.get('ids', [self.uuid]) # export project id
не надо ids брать из params, есть только self.uuid

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +        params['compressionLevel'] = params.get('compressionLevel', '5')
Вроде писал, что нужно использовать строки, а не числа

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +        params['overwriteExisting'] = params.get('overwriteExisting', True)
я не думаю что переписывать сущ файл по умолчанию хорошая идея

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +            :param params: export parameters
:param params: (optional) parameters

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +                    Normal = '5' (by default), Maximum = '7', Ultra = '9'.
compressionLevel: Compression level. Possible values are `Store`, `Fastest`, `Fast`, `Normal`(by default), `Maximum`, `Ultra`

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +                usePAGridFormat: bool: Make the exported project file compatible with the PaGrid.\
Export project in a PAGrid compatible format

2023-08-03 13:48 UTC, yatmanov commented on polyanalyst6api/project.py
> +                usedParsers: list: include the parsers used. Empty by default.
нужно привести к общему виду, где то есть двоеточие после типов, где то нет; где то описание начинается с большой буквы, где то с малой и тд

2023-08-03 14:26 UTC, stmikhayl commented on polyanalyst6api/project.py
> +    def _get_export_status(self, export_id: str) -> Dict[str, Any]:
![image](https://github.com/Megaputer/polyanalyst6api-py/assets/67823329/371b390b-bb66-484f-b453-2a2443cd1713)

2023-08-03 14:26 UTC, stmikhayl commented on polyanalyst6api/project.py
> +        params['multi'] = params.get('multi', False) # use the *.paar6 forma
подождем до конца пн. возможно, будут изменения в API.
Все остальное поправлю

2023-08-03 15:26 UTC, stmikhayl commented on polyanalyst6api/project.py
> +        params['overwriteExisting'] = params.get('overwriteExisting', True)
забыл добавить еще обработку исключения для случая, когда файл не может быть перезаписан - добавлю

2023-08-15 15:18 UTC, stmikhayl commented on polyanalyst6api/project.py
>              if status.get('progress', 100) == 100:
тут нужно другое условие (добавить проверку state) и убрать использование get

2023-08-17 08:10 UTC, yatmanov requested changes

2023-08-17 08:10 UTC, yatmanov commented on polyanalyst6api/project.py
> +            if status['state'] in ('Exported', 'Error'):
давай вернем status.get('state') обратно, этот ключ не всегда присутствует

2023-08-17 11:56 UTC, yatmanov requested changes

2023-08-17 11:56 UTC, yatmanov commented on polyanalyst6api/project.py
> +            :param wait: wait until the project export is completed. False by default.
нужно сдвинуть на один отступ влево

2023-08-17 11:56 UTC, yatmanov commented on polyanalyst6api/project.py
> +        Export project to a file system.
новая строка после

2023-08-17 11:56 UTC, yatmanov commented on polyanalyst6api/project.py
> +            :param file_path: str: Absolute path to the exported project. Also project can be exported on the Drive,\
нужно убрать тип
The folder location, name and extension of the destination file. The location can be absolute path or PolyAnalyst alias, i.e. `Open access folder` or `User home folder`. The file extension defines project format: `ps6`, `pa6`, `psar6`, `paar6`, `pagridar6`. For example, `D:\projects\example.pa6` or `@administrator@/example.pagridar6`

2023-08-17 11:56 UTC, yatmanov commented on polyanalyst6api/project.py
> +                usedParsers: list: Include the parsers used. Empty by default.
нужно убрать типы и написать их в комментах если нужно, например Список идентификаторов проектов
и нужно заменить by default на defaults to

2023-08-17 12:32 UTC, stmikhayl commented on polyanalyst6api/project.py
> +        params['ids'] =  [self.uuid] + params.get('ids', [])
оставить новый вариант или вернуть старый?

2023-08-18 06:46 UTC, merged