Add Project.load, Project._get_load_status methods. Edit method API.project
Megaputer/polyanalyst6api-py pull request #10
Opened 2023-10-17 09:18 UTC by stmikhayl

2023-10-18 14:32 UTC, stmikhayl commented on polyanalyst6api/project.py
> +            if status.get('status') not in ('Processing'):
статус Error нужно обрабатывать?

2023-10-25 06:45 UTC, yatmanov requested changes

2023-10-25 06:45 UTC, yatmanov commented on polyanalyst6api/project.py
> +        .. versionadded:: 0.30.1
версионирование идёт по semver. Здесь должно быть 0.31

2023-10-25 06:45 UTC, yatmanov commented on polyanalyst6api/project.py
> +            if status.get('status') not in ('Processing'):
? ниже же есть обработка

2023-10-25 13:06 UTC, stmikhayl commented on polyanalyst6api/project.py
> +            if status.get('status') not in ('Processing'):
да, добавил

2023-10-30 18:58 UTC, closed without merging