add report class
Megaputer/polyanalyst6api-py pull request #8
Opened 2023-09-20 11:38 UTC by stmikhayl

2023-09-21 15:47 UTC, yatmanov commented on polyanalyst6api/report.py
> +        self.reportUUID = reportUUID
давай оставим просто uuid

2023-09-21 16:15 UTC, yatmanov requested changes
надо бы добавить короткое описание каждому методу
А так всё здорово!

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/api.py
> +        return rprt
`return Report(self, uuid)`

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/api.py
> +    def report(self, reportUUID: str) -> Report:
просто uuid

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/report.py
> +    def publications(self) -> Publication:
`-> List[Publication]:`

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/report.py
> +        return comps
`return self.api.get('report/components', params={'reportUUID': self.uuid})`

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/report.py
> +        return slice_stats
`return  self.api.get('report/slice-statistics/export', params={'reportUUID': self.uuid})`

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/report.py
> +        self.api.get('report/slice-statistics/clear', params={'reportUUID': self.reportUUID})
тут неправильно. reportUUID нужно передавать в json

2023-09-21 16:15 UTC, yatmanov commented on polyanalyst6api/report.py
> +        self.api.post('report/slice-statistics/import',  slice_stats)
это тоже в json

2023-09-22 18:18 UTC, stmikhayl commented
> надо бы добавить короткое описание каждому методу А так всё здорово!

`.. versionadded:: 0.30.0` тоже добавить? :)

2023-09-25 11:39 UTC, yatmanov commented
> > надо бы добавить короткое описание каждому методу А так всё здорово!
> 
> `.. versionadded:: 0.30.0` тоже добавить? :)

добавь в описание класса, в каждый метод не надо

2023-10-06 09:43 UTC, yatmanov requested changes
надо добавить файл с описанием что сделано в папку .changes

2023-10-06 12:17 UTC, yatmanov requested changes

2023-10-06 12:17 UTC, yatmanov commented on polyanalyst6api/report.py
> +class Report():
class Report:

2023-10-06 12:17 UTC, yatmanov commented on .changes/add_class_report.feature
> +Added `report` method to `API` class.
в одном файле может быть только одно сообщение

2023-10-06 12:35 UTC, yatmanov approved these changes

2023-10-06 12:47 UTC, merged